# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='audio_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='pdf_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
