# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20161208_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preview_image_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
